version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT:-5000}:${PORT:-5000}"
    environment:
      - VITE_API_ENDPOINT=${VITE_API_ENDPOINT}
      - PORT=${PORT:-5000}
    env_file:
      - .env
